"""Generate a commented ``langstage.toml`` — the write side of the config surface.

``langstage config`` reads the resolved configuration (value, source, env var, and
TOML key for every field); ``langstage init`` writes a starter file from the *same*
metadata (``AppConfig._toml_map()`` + ``_env_map()`` + the dataclass defaults), so
the two stay in lockstep by construction and there is no README-vs-reality drift.
(gh #77)
"""
from __future__ import annotations

from dataclasses import MISSING, fields
from typing import Any

from langstage.config import AppConfig
from langstage_core.host.config import _env_pair  # canonical/legacy env-name resolver (same one `config` uses)

# Example values for fields whose default is ``None`` (nothing useful to show).
_EXAMPLES: dict[str, str] = {
    "agent_spec": '"my_agent.py:graph"',
    "show_canvas": "true",
    "show_files": "true",
}

# Section order for the generated file (any unlisted section is appended after).
_SECTION_ORDER = ["agent", "workspace", "server", "ui", "auth", "workflow"]

_HEADER = """\
# langstage.toml - generated by `langstage init`.
#
# Priority (highest wins): Python args > CLI args > env vars > this file > defaults.
# Every option is listed but commented out - uncomment and edit only what you need.
# The value shown is the built-in default (or an example); the env-var equivalent is
# noted after each key. Verify what any config actually resolves to with:
#
#     langstage config
"""


def _default_of(field) -> Any:
    if field.default is not MISSING:
        return field.default
    if field.default_factory is not MISSING:  # type: ignore[misc]
        return field.default_factory()  # type: ignore[misc]
    return None


def _toml_quote(s: str) -> str:
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{s}"'


def _render_value(name: str, value: Any) -> str:
    """Render a field default as a TOML scalar (ASCII-only; cp1252-safe)."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if value is None:
        return _EXAMPLES.get(name, '""')
    s = str(value)  # str or Path
    if len(s) > 80:
        s = s[:77] + "..."  # illustrative only (the line is commented out)
    return _toml_quote(s)


def _env_comment(name: str, env_map: dict) -> str:
    entry = env_map.get(name)
    if not entry:
        return ""
    canonical = _env_pair(entry[0])[0]  # normalize legacy DEEPAGENT_* declarations
    return f"  # env: {canonical}"


def render_langstage_toml(config_cls: type[AppConfig] = AppConfig) -> str:
    """Return a fully-commented ``langstage.toml`` covering every configurable key,
    grouped into its TOML section and annotated with its env-var equivalent."""
    toml_map = config_cls._toml_map()      # field -> "section.key" or "key"
    env_map = config_cls._env_map()        # field -> (ENV_VAR, caster)
    defaults = {f.name: _default_of(f) for f in fields(config_cls)}

    # Group fields by TOML section, preserving first-seen order.
    sections: dict[str, list[str]] = {}
    toplevel: list[str] = []
    for name, tkey in toml_map.items():
        if "." in tkey:
            sections.setdefault(tkey.split(".", 1)[0], []).append(name)
        else:
            toplevel.append(name)

    ordered = [s for s in _SECTION_ORDER if s in sections]
    ordered += [s for s in sections if s not in _SECTION_ORDER]

    lines: list[str] = [_HEADER]

    # Top-level (section-less) keys MUST precede any [section] header — in TOML a
    # bare key after a table header binds to that table, not the document root.
    if toplevel:
        for name in toplevel:
            value = _render_value(name, defaults.get(name))
            lines.append(f"# {name} = {value}{_env_comment(name, env_map)}")
        lines.append("")

    for section in ordered:
        lines.append(f"[{section}]")
        for name in sections[section]:
            leaf = toml_map[name].split(".", 1)[1]
            value = _render_value(name, defaults.get(name))
            lines.append(f"# {leaf} = {value}{_env_comment(name, env_map)}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
